name: RSS Notify

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install firebase-admin rss-parser

      - name: Register token
        run: node register.js "dyT1HSZnYNHf6zstN4kn8S:APA91bFCSyYzc9mQnPpt5rDOyFrgYErcDL03cdQ4fKHOJWSMa6cfVXSfPWlxsGG75z95iGD-Vf9N8r5i8u4nfpxxCzWZBCCvuyBkG-UWOd3Mo34PTlYR0yc"
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}

      - name: Run RSS Script
        run: node rss.js
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}

      - name: Commit last.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add last.json
          git commit -m "Update last.json" || echo "No changes"
          git push
